const assert=require('node:assert/strict'),fs=require('fs');
const {rename,statements}=require('./approved-layout.cjs');
const names=new Map([['root','scoped_root'],['bind','scoped_bind']]);
assert.equal(rename('root.bind root owner:root property:#root -- root\n"root.bind"',names),'scoped_root.bind scoped_root owner:scoped_root property:#root -- root\n"root.bind"');
assert.equal(rename('fn bind root key:#root = (root.bind root)',names),'fn scoped_bind scoped_root key:#root = (scoped_root.bind scoped_root)');
const source='\n        local root=undefined\n        on go pressed do if root!=undefined do (\n            local ignored=1\n        )\n                fn updateControls = (\n            root.enabled=true\n        )\n        fn bind layer = (updateControls())\n';
const parts=statements(source);
assert.equal(parts.length,4,'Indented rollout-scope functions must not become part of the preceding event');
assert.ok(parts[2].startsWith('        fn updateControls'));
assert.ok(!parts[1].includes('fn updateControls'));
const inventory=JSON.parse(fs.readFileSync('tools/ui/layers-control-inventory.json'));
const layout=JSON.parse(fs.readFileSync('tools/ui/approved-layout-manifest.json'));
assert.equal(layout.sections.length,11);
assert.equal(new Set(layout.sections.map(s=>s.name)).size,11);
const mapped=new Set(layout.sections.flatMap(s=>s.controls.map(c=>c.component+'/'+c.control)));
for(const [name,entries] of Object.entries(inventory.layer))for(const entry of entries)assert.ok(mapped.has(name+'/'+entry.name),name+'/'+entry.name);
for(const [name,key] of Object.entries({surface:'flow_surfaceUI',manager:'flow_layersUI',previewUI:'flow_previewUI',diagnostics:'diagnosticsUI'}))for(const entry of inventory.general[name])assert.ok(mapped.has(key+'/'+entry.name),key+'/'+entry.name);
const script=fs.readFileSync('scripts/AminScatterObject.ms','utf8');
assert.equal((script.match(/fn diversityUI_updateControls =/g)||[]).length,3);
assert.ok(!/\bupdateControls\(\);diversityUI_updatePattern\(\)/.test(script));
assert.ok(script.includes('if isProperty control #width then control.width=available'));
assert.ok(script.includes('if controlsReady and not binding and root!=undefined and sourceContainersUI_controlsReady'));
assert.ok(!script.includes('Multi-set layers support Random and Clusters.'),'The unified engine supports per-set Line/Analyzer choices; the UI must not retain the old gate');
assert.ok(script.includes('then cellWidth-12 else 0'),'Spinner position addresses arrows, not the compound control origin');
assert.ok(script.includes('label setsUI_targetList_caption "Surface"'));
assert.ok(!script.includes('brushUI_strokeList'),'Per-stroke editing is retired');
assert.equal(layout.sections[0].name,'managerUI');
assert.equal(layout.sections[1].name,'surfacesUI');
assert.ok(script.includes('label sourceContainersUI_containersList_caption "Rectangles"'),'List captions must keep their own layout row');
assert.ok(!script.includes('(dotNetClass "System.Windows.Forms.Cursor").Position'),'MAXScript aliases Position to pos; drag must use event coordinates');
const gripMoves=[...script.matchAll(/on (\w+_grip) MouseMove sender args do ([^\n]+)/g)];
assert.ok(gripMoves.length>=20,'Both native and popup list grips must be covered');
for(const [,id,body] of gripMoves)assert.equal(body,'moveListDrag sender args',id+': idle mouse moves must not trigger an unconditional layout');
assert.ok(script.includes('close do (stopListDrag();'),'Closing a view must release mouse capture');
assert.equal((script.match(/if changed and controlsReady do layout\(\);true\)/g)||[]).length,3,'All three brush views skip unchanged status layout');
console.log('PASS: namespaces, declaration scope, complete field mapping, control property guards and cold event guards');
