# Shared host configuration. Each Max year requires its own build directory/SDK.
set(CYRUS_MAX_YEAR "2026" CACHE STRING "Target 3ds Max year (2026 or 2027)")
set_property(CACHE CYRUS_MAX_YEAR PROPERTY STRINGS 2026 2027)
if(NOT CYRUS_MAX_YEAR MATCHES "^(2026|2027)$")
  message(FATAL_ERROR "Only Max 2026 and 2027 build configurations are implemented")
endif()
set(MAXSDK_ROOT "C:/Program Files/Autodesk/3ds Max ${CYRUS_MAX_YEAR} SDK/maxsdk" CACHE PATH "Matching 3ds Max SDK")
if(NOT EXISTS "${MAXSDK_ROOT}/include/max.h" OR NOT EXISTS "${MAXSDK_ROOT}/include/maxversion.h")
  message(FATAL_ERROR "Set MAXSDK_ROOT to the matching ${CYRUS_MAX_YEAR} maxsdk directory")
endif()
file(STRINGS "${MAXSDK_ROOT}/include/maxversion.h" _cyrus_sdk_year REGEX "^#define MAX_PRODUCT_YEAR_NUMBER +[0-9]+")
if(NOT _cyrus_sdk_year MATCHES "MAX_PRODUCT_YEAR_NUMBER +${CYRUS_MAX_YEAR}($|[^0-9])")
  message(FATAL_ERROR "MAXSDK_ROOT does not match CYRUS_MAX_YEAR=${CYRUS_MAX_YEAR}: ${_cyrus_sdk_year}")
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "Cyrus requires an x64 build")
endif()
if(CYRUS_MAX_YEAR GREATER_EQUAL 2027)
  set(CMAKE_CXX_STANDARD 20)
else()
  set(CMAKE_CXX_STANDARD 17)
endif()
set(CMAKE_CXX_STANDARD_REQUIRED ON)
function(cyrus_max_target target)
  target_include_directories(${target} SYSTEM PRIVATE "${MAXSDK_ROOT}/include")
  target_link_directories(${target} PRIVATE "${MAXSDK_ROOT}/lib/x64/Release")
  target_compile_definitions(${target} PRIVATE UNICODE _UNICODE NOMINMAX CYRUS_MAX_YEAR=${CYRUS_MAX_YEAR})
endfunction()
