"""Emit the compact, human-curated research ledgers; not production tooling."""
from research_tools import ROOT,HERE
import csv,re

def local(p):return (ROOT/p).as_posix()
def evidence(p):return (HERE/'evidence'/p).as_posix()
def emit(name,cols,rows):
    fixes={'fulloperation':'full operation','fulloracleprototype':'full oracle prototype','currentbaseline':'current baseline',
           'small/large':'small/large','undercontendedhost':'under a contended host','latencygain':'latency gain',
           'host-boundoperation':'host-bound operation','Synchronouspath':'Synchronous path','startupdominance':'startup dominance',
           'interactiontarget':'interaction target','OptimizedCPUonly':'Optimized CPU only','onebackend/oneworkload':'one backend / one workload',
           'comparequiet/contended':'compare quiet/contended','hostpublication':'host publication','preapprovedvisualoracle':'preapproved visual oracle',
           'assumedinterop':'assumed interop','deploymentcost':'deployment cost','defeatsvalue':'defeats value',
           'optionalbackend':'optional backend','maintainablehardwareenvelope':'maintainable hardware envelope',
           'narrowalternatives':'narrow alternatives','namedworkflow':'named workflow','equalwork':'equal work',
           'lifecycleproof':'lifecycle proof','wrongvisibility':'wrong visibility','unsupportedclaim':'unsupported claim',
           'stopsbeforetiming':'stops before timing','currentrejection':'current rejection','explicitworkflow':'explicit workflow',
           'qualitywins':'quality wins','privateinternalsclaims':'private internals claims','lowtiming':'low timing',
           'outputchange':'output change','unknownbenefit':'unknown benefit','contentionregression':'contention regression',
           'contendedhost':'contended host','transactionreuse':'transaction reuse','measuredstart':'measured start',
           'fallbackslow':'fallback slowly','hostthread':'host thread','tiny-cluster':'tiny-cluster',
           'coalescing/transactionreuse':'coalescing / transaction reuse','current0.62':'current 0.62',
           'colors/shading/count':'colors/shading/count','changesface':'changes face','small-input/cap':'small-input/cap',
           'oldpath':'old path','nativework':'native work','noGPU':'no GPU','GPUresources':'GPU resources',
           'repeatableworkload':'repeatable workload','quiet/IR':'quiet / IR','unsupported-range':'unsupported-range',
           'refreshrisk':'refresh risk','full editgain':'full edit gain'}
    rendered=[]
    for row in rows:
        out=[]
        for col,value in zip(cols,row):
            if col not in {'id','claim_ids','experiment_or_run_id','source_locator'}:
                for a,b in fixes.items():value=value.replace(a,b)
                value=re.sub(r'(?<=[A-Za-z])(?=\d)|(?<=\d)(?=[A-Za-z])',' ',value)
                value=value.replace('P 95','P95').replace('FP 64','FP64').replace('D 3 D 11','D3D11').replace('x 64','x64')
            out.append(value)
        rendered.append(out)
    with (HERE/name).open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.writer(f);w.writerow(cols);w.writerows(rendered)

# id, status, class, version, source date, claim, locator, applicability, contradiction, next
claims=[
('C01','verified','A','Scatter 0.62 working tree','2026-10-01','CPU filtering/transforms/prepared bands and narrow cluster ranges already implemented',local('AminScatter/src/max_bridge.cpp')+' :: cyrusFilterSourceRows_cf / cyrusApplySourceTransforms_cf; '+local('AminScatter/src/scatter.cpp')+' :: scatter; prepared_band.inc','Current source; generator ownership matters','Older roadmap entries are partly completed','Profile remaining exclusive costs before more rewrites'),
('C02','passed','B','SDK 2026/2027; MSVC 14.38','2026-10-01','Eight Scatter and one Analyzer native suites pass in each fresh build',evidence('ctest-2027-AminScatter.txt')+'; '+evidence('ctest-2026-AminScatter.txt')+'; ctest-*-CyrusSurfaceAnalyzer.txt','Native tests in Release; research builds','Not Max 2026 runtime or renderer qualification','Run intended host/renderer matrix'),
('C03','passed','B','Max 2027.1 / 29.1.0.11426','2026-10-01','Three original isolated host fixtures pass',evidence('max2027_smoke-run.json')+'; '+evidence('compute_performance_smoke-run.json')+'; '+evidence('viewport_performance_smoke-run.json'),'Synthetic fresh batch hosts; disposable copied scripts/scenes','No actual GPU-completed frame or retained display test','Visual/interactive and long lifecycle qualification'),
('C04','verified','B','Scatter 0.62 Max2026/2027','2026-10-01','Generator byte parity and package ZIP/manifest/source-script checks pass',evidence('generator-parity.json')+'; '+evidence('package-identity.json'),'Current local packages and script files','File identity is not in-memory script identity','Record runtime script identity before comparisons'),
('C05','observed','B;G','Max 2027.1; Corona modules 15.0.671720','2026-10-01','Live process loaded module path matches installed 0.62 native hash; script disk hash matches; in-memory script uninspected',evidence('loaded-modules.json')+'; '+evidence('machine.json'),'Original PID 34464; read-only inventory','Scene filename contains Max2026 but host is 2027; loaded Corona is not render evidence','Use fresh comparison host and runtime identities'),
('C06','historical; hash/arithmetic audited','C;B','Scatter 0.61 native switch','2026-10-01','Same 6284 proxies/37704 triangles; GW boundaries 6284 to 44; step median 88.10405 to 30.16225 ms',local('docs/Viewport_Performance_Implementation_2026-10-01.md')+'; '+evidence('historical-audit.json'),'180 steps per condition; three repeats; no rebuilds','No GPU draw-call counter/completion fence; baseline uses candidate script','Repeat current vs proposed with correct frame attribution'),
('C07','historical; hash/arithmetic audited','C;B','Scatter 0.61 vs 0.62','2026-10-01','Held step median 34.48985 to 31.33575 ms; callback 11.7631 to 7.8747 ms',local('docs/Viewport_Performance_Round2_2026-10-01.md')+'; '+evidence('historical-audit.json'),'Held matrix; 180 samples per condition','Normal median nearly unchanged; retained exploratory meshes had brightness mismatch','Do not forecast FPS; test full interaction and parity'),
('C08','observed; bottleneck unproven','A;F;G','Current generated controller/native bridge','2026-10-01','Area plus placement can repeat extraction; row packing and proxy/source preparation remain',local('AminScatter/scripts/AminScatterObject.ms')+' :: placements/populationCount/refreshPreview; '+local('AminScatter/src/max_bridge.cpp')+' :: meshOf/aminScatterSurfaceArea_cf','Editing/rebuild; source-dependent cost','No exclusive current artist trace in this investigation','X02 count extraction/copies and generations'),
('C09','observed; scoped behavior tested','A;B','Scatter 0.62 / Analyzer 0.14','2026-10-01','Held layer synchronization deferral and event-batch redraw coalescing exist; Manual/Undo paths differ',local('AminScatter/tools/ui/viewport-performance.cjs')+'; '+local('AminScatter/tools/ui/performance.cjs')+'; '+evidence('viewport_performance_smoke-result.txt'),'Do not add a duplicate generic coalescer','Other timers and Analyzer can still issue work','X02 input-to-first-correct-generation trace'),
('C10','measured; drop-in rejected','A;B','Current SurfaceTree and closest','2026-10-01','Tree build+queries lose on 2 triangles; help larger grids; equal-distance hint can change face identity',evidence('projection-summary.json')+'; '+(HERE/'projection_probe.cpp').as_posix(),'2048 planar queries; two warmups/nine pairs; standalone only','Random queries matched; adversarial tie failed ID; not full scatter','X03 tie/pruning/error oracle plus workflow relevance'),
('C11','measured','A;B','Current executor; Ryzen 5600X','2026-10-01','17 valid cases preserve output hashes serial/auto; eligible 32k/100k roughly halve native time',evidence('threads-summary.json')+'; '+local('AminScatter/include/execution.h'),'21 samples/policy; three reversed blocks; no render load controlled','Several cases remain serial; 4095 vs4096 threshold; original trial order sorted','Measure 1/2/4 and renderer contention before default change'),
('C12','compile/link verified; runtime absent','B;D;G','Autodesk SDK 2026/2027','SDK-year documentation; publication not stated','IObjectDisplay2 and ViewportInstancing InstanceDisplayGeometry compile/link; optimesh.lib included',evidence('sdk-probes.json')+'; https://help.autodesk.com/cloudhelp/2027/ENU/MAXDEV-CPP-API-REF/class_max_s_d_k_1_1_graphics_1_1_viewport_instancing_1_1_instance_display_geometry.html ; https://help.autodesk.com/cloudhelp/2027/ENU/MAXDEV-CPP-API-REF/class_max_s_d_k_1_1_graphics_1_1_i_object_display2.html','Viewport only; exact headers and probe in report §6','Sample missing locally; embedded snippet numPositions differs from struct; no display execution','X01 visual owner/lifetime/style/picking prototype'),
('C13','documented; 2027 guide unavailable','D;G','Autodesk 2026 guide; 2027 local headers','Not stated','General Max thread-safety restrictions; custom Nitrous callbacks need self-contained data','https://help.autodesk.com/cloudhelp/2026/ENU/MAXDEV-Developer/files/best_practices/thread_safety.html ; https://help.autodesk.com/cloudhelp/2026/ENU/MAXDEV-Developer/files/3ds_max_sdk_features/viewports_and_graphics_windows/nitrous/about_renderitem.html','Keep host/GC/reference/evaluation work outside numeric workers; respect callback-specific contract','Renderer callback exceptions are not blanket permission; 2027 guide fetch failed','Verify version-specific contract for each new concurrent host call'),
('C14','documented','D','MSVC VS2022 / msvc-170','Publication/update not captured','FP contraction/reassociation can change bits; precise default is not arbitrary FP-environment assurance','https://learn.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-170 :: Arguments and floating-point environment','Exact seeded geometry/CPU SIMD proposals','Older compiler variants on same page differ; workers copying environment is not compiler proof','Preserve operation order; qualify flags/ISA/rounding states'),
('C15','documented; local GPU crossover unknown','D;F;G','CUDA Best Practices 13.4','Versioned guide; date not captured','Count transfers/setup/readback; overlap requires suitable hardware/pinned buffers/streams and independent work','https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html :: 10.1-10.1.2','GPU-compute model; not a recommendation to install CUDA','Device residency unproven at Max boundary; no backend benchmark','Reopen only for measured complete-operation benefit'),
('C16','documented; local runtime untested','D;G','OpenCL unified refs; D3D11 sharing 1.0.0','Sharing revision 2020-04-21; query date not stated','FP64 is optional; D3D11 sharing uses explicit device/resources/acquire/release','https://registry.khronos.org/OpenCL/specs/unified/refpages/man/html/clGetDeviceInfo.html :: DOUBLE_FP_CONFIG; https://registry.khronos.org/OpenCL/specs/unified/refpages/man/html/cl_khr_d3d11_sharing.html','Query actual device/driver features, not API label','No demonstrated sharing with Nitrous or optional runtime packaging','Capability/interop proof before a compute spike'),
('C17','documented; deferred','D;F','DirectCompute / D3D11','Publication/update not captured','Compute shader double support depends on feature capability','https://learn.microsoft.com/en-us/windows/win32/direct3d11/direct3d-11-advanced-stages-compute-shader :: D3D11 hardware','Potential graphics-adjacent backend only','Access to Nitrous device/context not established','Do not add until resource ownership and workload proven'),
('C18','documented; deferred','D;F','SYCL 2020 revision 12','Publication/update not captured','SYCL exposes platform/backend and optional fp64 device capabilities','https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html :: 4.6 and 5.5','Alternative ecosystem, not another required backend','Specification does not guarantee deployed compiler/driver coverage','No implementation until a specific need defeats simpler CPU path'),
('C19','documented; deferred','D;F','oneAPI 1.4 provisional rev1 task_arena','Provisional latest; date not stated','Arena concurrency bound applies inside that arena','https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onetbb/source/task_scheduler/task_arena/task_arena_cls :: Description','Future scheduler experiment, not host-wide CPU governor','oneTBB main docs navigation loaded but subsequent body fetch 404; provisional spec used','Pin/test a supported library only if launch overhead warrants it'),
('C20','documented with qualification','D','tyFlow Display docs; Max2020+ UV note','Publication/update not stated','Nitrous instancing features/fallbacks and display reductions are documented','https://docs.tyflow.com/tyflow_particles/operators/display/ :: Geometry and Nitrous notes','Borrow capability fallback and explicit quality controls','Broad UV warning qualified later by single-channel override on Max2020+; private code unknown','Test required attributes on intended host; no private algorithm inference'),
('C21','documented','D','Chaos Scatter / Corona for Max','2025-11-14 update','Instances retain costs; extra LOD sources can increase memory; clumps/clipping trade quality and coverage','https://support.chaos.com/hc/en-us/articles/4953457092625-How-to-use-Chaos-Scatter-with-Corona-for-3ds-Max-Performance-and-Troubleshooting :: memory/LOD/clumps/clipping','Workload/resource accounting only','Does not expose private algorithms or prove Cyrus renderer compatibility','Measure own transport/renderer scene outputs'),
('C22','observed; wait latency unmeasured','A;G','Scatter 0.62 / Analyzer 0.14','2026-10-01','Release timer 200ms; Analyzer timer/event separate; IR patch waits for stable key before restart',local('AminScatter/tools/ui/performance.cjs')+' :: CyrusReleaseTick and CyrusPFStableSince; '+local('CyrusSurfaceAnalyzer/scripts/CyrusSurfaceAnalyzer.ms')+' :: timer/live callback','Separate deliberate waits from active compute','Timer intervals are not guaranteed total latency','X02 causal timing; do not tune blindly'),
('C23','documented; proposed use only','D;G','Windows GPUView / D3D11; PresentMon main docs','GPUView 2025-11-14; timestamp 2024-02-22; PresentMon update not stated','ETW GPU scheduling, actual presents and timestamp validity distinguish submission/completion','https://learn.microsoft.com/en-us/windows-hardware/drivers/display/using-gpuview ; https://github.com/GameTechDev/PresentMon/blob/main/README-CaptureApplication.md ; https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_query_data_timestamp_disjoint','Future instrumented host comparison','No captures run; wrong swap chain and observer overhead can mislead','Correlate viewport presents with accepted generation and measure overhead'),
('C24','documented; proposed use only','D;G','MSVC AddressSanitizer / Windows x64','Publication/update not captured','AddressSanitizer supported; do not assume MSVC thread sanitizer from future list','https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170 :: support/use','Standalone native memory/fault tests first','Not a race detector or host-threading validation; not run here','Check installed runtime; isolated ASan qualification'),
('C25','observed and measured sizes','A;B;F','Current x64 types/cache','2026-10-01','Triangle144 and Instance112 bytes; proxy16/64MiB limits cover added payload only',evidence('projection-summary.json')+'; '+local('AminScatter/src/preview_batches.inc'),'Model peak copies/GC generations/VRAM separately','96GiB workstation cannot qualify32GB; WMI GPU AdapterRAM under-reports','Physical32GB/renderer pressure and resource envelope'),
('C26','preservation audit','B','Working tree at f3f30ce plus original changes','2026-10-01','Production source preservation checked against initial 113-file fingerprint',evidence('source-fingerprint.json')+'; '+evidence('preservation.json'),'Only new research docs/tools/evidence and scratch intended','Snapshot is dirty-tree identity, not pristine commit','Check final artifact manifest and status delta'),
('C27','observed; cost unmeasured','A;G','Current proxy/Mesh/Point Cloud paths','2026-10-01','Full Mesh and Point Cloud have separate prep/display costs and semantics',local('AminScatter/src/geometry_preview.inc')+'; '+local('AminScatter/src/preview.cpp')+'; '+local('AminScatter/scripts/AminScatterObject.ms')+' :: refreshPreview','Do not extrapolate simple-proxy result to detailed materials/markers','Current solid diagnostic geometry is not all source materials/UVs','Separate workload/profile and visual contract'),
('C28','historical and uncontrolled separated','C;E;G','Original artist scene vs synthetic demo','2026-10-01 context','20-to80 and23-to150 FPS reports refer to different uncontrolled workloads',local('GPT 6 Pro Research Brief/REFERENCE - Project Context.txt')+' :: Evidence with boundaries','Useful motivation only; no controlled FPS claim','Demo initially loaded stale0.60; same counts do not mean same work','Controlled current baseline before future speed claims'),
('C29','historical hash audit','C;B','CPU implementation0.60','2026-10-01','Historical full refresh3.98-4.05s to1.01-1.17s;60 recorded output pairs agree',local('docs/Performance_Implementation_2026-10-01.md')+'; '+evidence('historical-audit.json'),'Five states/five trials; source artifacts present and hashes checked','Not rerun and not input-to-visible or completed frames','X02 current workflow trace'),
]
updates={'C14':'2021-11-22 update','C17':'2021-04-09 update','C24':'2026-05-28 update'}
claims=[tuple(list(x[:4])+[updates.get(x[0],x[4])]+list(x[5:])) for x in claims]
emit('claims.csv',['id','status','evidence_class','relevant_version','publication_or_update_date','claim','source_locator','applicability','contradictions_or_limits','next_verification','access_or_observation_date'],[list(x)+['2026-10-01'] for x in claims])

decisions=[
('D01','experiment rank1','X01','A;B;C;D;F;G','C06,C07,C12,C27','Retained simple-proxy display','Keep current0.62 batches','Historical residual submission cost; SDK compile/link only','Brighter retained pilot/invisible legacy attempts; native owner integration unknown','Existing display payload/caps + new separately boundedGPU resources; no compute backend','Copy scenes; same pyramid geometry/shading/count; current vs retained frame/interaction times','Zero output/lifecycle differences; proposed >=20% operation median gain; P95 no >5% regression','Any visibility/shading mismatch; not CPU submission limited; large migration required','Single old-path switch; release resources','Medium investigation value; low speed forecast','Correct same-quality host result with full-operation gain','REPORT.md §6 and D01; evidence/sdk-probes.json'),
('D02','experiment rank2','X02','A;B;C;F;G','C08,C09,C22','Causal edit trace then only proven duplicate-work removal','Current synchronous/event-batched code','Duplicate extraction opportunity and current rules confirmed; no full causal trace','Current coalescing may already suffice; new cache can stale','Opt-in bounded trace; proposed transaction-owned64MiB cap; no executor','Single/layered copied scenes, input->generation->exclusive spans->first visible; exact oracle','Trace overhead<2%; repeated stage>=10%; proposed >=15% full edit median gain; no stale result','No material duplication; trace overhead dominates; Manual/Undo violation','Disable tracing/reuse; destroy transaction snapshot','High attribution value; low specific optimization certainty','Measured native/timer/host dominance changes target','REPORT.md D02; evidence/compute_performance_smoke-result.txt'),
('D03','experiment rank3; unmodified reuse rejected','X03','A;B;F;G','C10','Tie-correct movement projection tree','Keep exhaustive scan','Real tree wins larger grids but loses2tri; adversarial tie changesface','No dense artist bottleneck established; pruning/near-ties unqualified','O(T) evaluation-owned tree; proposed64MiB incremental cap; no dependency','Exact face/position/UV/source/error differential then full placement/refresh sweep','Zero bit/ID mismatches; proposed >=25% nominated placement median gain; useful artist contribution','Any tie/pruning mismatch or tiny production surfaces; <10% refresh share defers','Select old scan universally; leave relaxation behavior unchanged','High synthetic gain/tie risk; low artist relevance','Measured dense-surface projection dominance','REPORT.md D03; evidence/projection-summary.json'),
('D04','keep','R01,R02,R03','A;B;C;F','C01,C02,C03,C11,C25','Current bounded executor/proxycache','Serial/old-draw controls','Eligible workload gains/exact outputs; host fixture pass','Renderer/hybridCPU/32GB unknown; caps can fallbackslow','Existing caps plus base allocations; no new dependency','1/2/4 participants; quiet/IR; small/large; fallback saturation','Preserve exact oracle; investigate >max(5%,2ms) full-operation regression','Correctness failure or repeatable workload regression','Serial/old drawing','Medium-high in tested scope','Contention/hardware evidence can change defaults','REPORT.md D04; evidence/threads-summary.json'),
('D05','defer','future only','A;B;D;F;G','C09,C11,C13,C19,C22','Persistent executor/oneTBB/async','Synchronous coalescing/transactionreuse','No demonstrated launch or latency bottleneck','Snapshot/shutdown/host safety outweigh unmeasured value','Bound active/pending/snapshot storage; pinned dependency release if used','Measure launch queue cancel publication and lifecycle undercontendedhost','Proposed>=20% full edit gain; zero stale/lost generation','Host-boundoperation or no meaningful latencygain','Synchronouspath','High deferral confidence','Measured startupdominance or unmet interaction target','REPORT.md §5/D05'),
('D06','defer','future onebackend/oneworkload','A;B;D;F;G','C11,C15,C16,C17,C18','GPU computation','OptimizedCPUonly','Transfer/ownership costs not measured; no backend selected','No device-resident Max/PFlow result contract','Staging+VRAM+driver/runtime/compiler support; optionalCPUfallback','Count setup/upload/kernel/sync/download/hostpublication; comparequiet/contended','Proposed>=25% full-operation median gain; no tail/contention regression; exact/preapprovedvisualoracle','No supported-range crossover; assumedinterop; deploymentcost defeatsvalue','Disable optionalbackend; CPU result','High in no-backend-yet','Verified crossover and maintainablehardwareenvelope','REPORT.md §7/D06'),
('D07','reject for present task','none','A;B;C;F;G','C06,C07,C10,C28','Broad rewrite/allcores/unequalqualitywins/privateinternalsclaims','Focused existing code and experiments','No measured need; some comparisons demonstrably invalid','Cannot infer correct display from lowtiming','Large migration or outputchange; unknownbenefit','Require narrowalternatives fail namedworkflow then fulloracleprototype','No promotion without equalwork/fulloperation/lifecycleproof','Wrongvisibility/count/unsupportedclaim stopsbeforetiming','Currentbaseline','High currentrejection','New explicitworkflow evidence, not technology preference','REPORT.md D07'),
]
emit('decisions.csv',['id','status','experiment_or_run_id','evidence_class','claim_ids','artist_problem_and_candidate','simpler_alternative','evidence','strongest_objection_or_contradiction','cost_ownership_dependencies','falsifiable_test_and_oracle','proposed_acceptance','rejection_and_stop','rollback','confidence','reversal_evidence','source_locator','date','relevant_version'],[list(x)+['2026-10-01','Scatter0.62/Analyzer0.14; Max2027.1 tested; SDK2026/2027'] for x in decisions])
print('Wrote',len(claims),'claims and',len(decisions),'decisions')
